[package]
name = "sable_mir"
version = "0.1.0"
edition = "2024"

[dependencies]
sable_parser = { workspace = true }
smallvec = { workspace = true, features = ["serde"] }
pretty = { workspace = true }
