[package]
name = "sable_mir"
version = "0.1.0"
edition = "2024"

[features]
serde = []

[dependencies]
sable_parser = { workspace = true }
serde = { workspace = true, features = ["derive"] }
smallvec = { workspace = true, features = ["serde"] }
ariadne = { workspace = true }
